### ISSUE TITLE
 Tests: 9 failed

### ISSUE THREAD

**Issue by Hellseher** [NASA-Planetary-Science/sbpy#398] opened 2024-07-09 19:45 UTC
This is a follow up issue to https://github.com/NASA-Planetary-Science/sbpy/issues/397.

I've managed to make tests running by providing
`--ignore=sbpy/spectroscopy/tests/test_specgrad.py` option to `pytests` . Now
I've got tests started but eventually failed with following trace (2023 LoC):
[sbpy-398-20240709204851.txt](https://github.com/user-attachments/files/16149606/sbpy-398-20240709204851.txt)

**Comment by mkelley** [comment] 2024-07-10 19:52
Thanks, this better shows the root cause for #397, and will be fixed with PR #400.

**Closed** 2024-07-19 13:49 UTC
Labels: bug
