### ISSUE TITLE
issue report: astroquery/imcce/core.py

### ISSUE THREAD

**Issue by bcarry** [NASA-Planetary-Science/sbpy#268] opened 2020-08-07 09:30 UTC
**High-level problem description**

The simple cone-search query with Skybot failed, apparently because Skybot API place a "-" in the Number column for each non-numbered asteroid

**What did you do?**

from astropy.coordinates import SkyCoord
from astroquery.imcce import Skybot
from astropy import units as u
from astropy.time import Time

epoch = Time( '2020-06-01T00:00:00.0', format='isot')
field = SkyCoord(81.9843, 24.391615, unit=u.deg)
ssos = Skybot.cone_search(field, 0.15*u.deg, epoch)

**What did you expect?**

As astropy Table with the result of skybot query (21 entries)

**What did really happen?**

Traceback (most recent call last):
  File "./test_sb.py", line 10, in <module>
    ssos = Skybot.cone_search(field, 0.15*u.deg, epoch)
  File "/home/bcarry/anaconda3/lib/python3.7/site-packages/astroquery/utils/class_or_instance.py", line 25, in f
    return self.fn(obj, *args, **kwds)
  File "/home/bcarry/anaconda3/lib/python3.7/site-packages/astroquery/utils/process_asyncs.py", line 29, in newmethod
    result = self._parse_result(response, verbose=verbose)
  File "/home/bcarry/anaconda3/lib/python3.7/site-packages/astroquery/imcce/core.py", line 651, in _parse_result
    results['Number'] = [int(float(n)) for n in results['Number']]
  File "/home/bcarry/anaconda3/lib/python3.7/site-packages/astroquery/imcce/core.py", line 651, in <listcomp>
    results['Number'] = [int(float(n)) for n in results['Number']]
ValueError: could not convert string to float: '-'

** Proposed patch **
Adding the following code just before line 651 on imcce/core.py solves the issue:
results['Number'][ results['Number']=='-' ] = 0

But IAU numbers should not be "0". So this is only a dirty solution. It lets the module go through, and return an astropy table with 21 entries

**Provide information on your environment:**
operating system and version: Linux (Ubuntu 18.04.4 LTS)
sbpy version: 0.2
astropy version: 0.3.10
numpy version: 1.19.1

**Comment by mkelley** [comment] 2020-08-08 14:53
Hi @bcarry  This looks like an astroquery issue, rather than an sbpy issue, so I'm closing it here.  However, the returned table column should be masked when the number is missing.  I tried reproducing the error, but could not, even after downgrading astropy and astroquery.  (Did you mean astropy v0.3.10, or astroquery v0.3.10?)  I recommend trying to upgrade astroquery and 
astropy.  sbpy 0.2 should work with astropy 3.x and (I hope) any recent astroquery version.  If you still have errors, please open an issue on astroquery.

**Closed by mkelley** 2020-08-08 14:53 UTC
Labels: potential bug
